#!/bin/bash
set -e

USERNAME="$(whoami)"

# ============================
# Accounts from command line
# ============================
# Usage:
#   script.sh "pattern:name:email" ["pattern:name:email" ...]
#
# Example:
#   ./script.sh "gh-personal:jonnyd:john@example.com" "gh-work:John Doe:john@business.com"

if [ "$#" -eq 0 ]; then
    echo "Usage:"
    echo "  $0 \"pattern:name:email\" [\"pattern:name:email\" ...]"
    exit 1
fi

ACCOUNTS=("$@")

# Validate account format
for account in "${ACCOUNTS[@]}"; do
    if [[ "$account" != *:*:* ]]; then
        echo "Invalid account format: $account"
        echo "Expected: pattern:name:email"
        exit 1
    fi
done

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Paths
HOOKS_PATH="$HOME/.git-hooks"
SSH_PATH="$HOME/.ssh"

# Helper functions
print_header() {
    echo -e "\n${BLUE}===================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}===================================================${NC}\n"
}

print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠ $1${NC}"; }
print_error() { echo -e "${RED}✗ $1${NC}"; }
print_info() { echo -e "${BLUE}ℹ $1${NC}"; }

# Check dependencies
check_dependencies() {
    print_header "Checking Dependencies"

    local missing=()
    command -v git &>/dev/null || missing+=("git")
    command -v ssh-keygen &>/dev/null || missing+=("ssh-keygen")

    if [ ${#missing[@]} -ne 0 ]; then
        print_error "Missing required dependencies: ${missing[*]}"
        exit 1
    fi

    print_success "All dependencies found"
}

# Create hooks directory
create_hooks_directory() {
    print_header "Step 1: Creating Global Git Hooks Directory"

    print_info "Global hooks path: $HOOKS_PATH"

    if [ -d "$HOOKS_PATH" ]; then
        print_warning "Hooks directory already exists"
    else
        mkdir -p "$HOOKS_PATH"
        print_success "Created hooks directory"
    fi
}

# Generate hook script
generate_hook_script() {
    local script="#!/bin/sh
remote_url=\$(git config --get remote.origin.url)
"

    local first=true
    for account in "${ACCOUNTS[@]}"; do
        IFS=':' read -r pattern name email <<<"$account"

        if $first; then
            script+="if echo \"\$remote_url\" | grep -q \"$pattern\"; then
    git config user.name \"$name\"
    git config user.email \"$email\"
"
            first=false
        else
            script+="elif echo \"\$remote_url\" | grep -q \"$pattern\"; then
    git config user.name \"$name\"
    git config user.email \"$email\"
"
        fi
    done

    script+="fi
exit 0"
    echo "$script"
}

# Create hooks
create_hook() {
    local name="$1"
    local step="$2"

    print_header "$step"

    local hook_file="$HOOKS_PATH/$name"
    print_info "Creating $name hook"

    generate_hook_script >"$hook_file"
    chmod +x "$hook_file"

    print_success "$name hook created"
}

# Configure Git hooks
configure_git_hooks() {
    print_header "Step 5: Configuring Git Global Hooks"

    git config --global core.hooksPath "$HOOKS_PATH"
    print_success "Global Git hooks configured"
}

# Add Git alias
add_git_alias() {
    print_header "Step 6: Adding Git Alias"

    git config --global alias.set-identity "!$HOOKS_PATH/post-checkout"
    print_success "Added 'git set-identity' alias"
}

# Generate SSH keys
generate_ssh_keys() {
    print_header "Step 7: Generating SSH Keys"

    mkdir -p "$SSH_PATH"
    chmod 700 "$SSH_PATH"

    for account in "${ACCOUNTS[@]}"; do
        IFS=':' read -r pattern name email <<<"$account"

        local key_name="${pattern//github-/}"
        key_name="${key_name//gitlab-/}"
        local key_path="$SSH_PATH/id_ed25519_$key_name"

        if [ -f "$key_path" ]; then
            print_warning "SSH key exists, skipping: $key_path"
            continue
        fi

        print_info "Generating SSH key for $pattern ($email)"
        ssh-keygen -t ed25519 -C "$email" -f "$key_path" -N ""

        print_success "Generated SSH key: $key_path"
    done
}

# Configure SSH
configure_ssh() {
    print_header "Step 8: Configuring SSH"

    local ssh_config="$SSH_PATH/config"

    if [ -f "$ssh_config" ]; then
        local backup="$ssh_config.backup.$(date +%s)"
        cp "$ssh_config" "$backup"
        print_warning "Existing SSH config backed up to $backup"
    fi

    local config="# Generated by Git Multi-Account Setup Script
# Generated on: $(date)

"

    for account in "${ACCOUNTS[@]}"; do
        IFS=':' read -r pattern name email <<<"$account"

        local key_name="${pattern//github-/}"
        key_name="${key_name//gitlab-/}"
        local key_path="$SSH_PATH/id_ed25519_$key_name"

        config+="# $name ($email)
Host $pattern
    HostName github.com
    User git
    IdentityFile $key_path
    IdentitiesOnly yes

"
    done

    echo "$config" >>"$ssh_config"
    chmod 600 "$ssh_config"

    print_success "SSH configuration updated"
}

# Display public keys
display_public_keys() {
    print_header "Step 9: Public SSH Keys"

    for account in "${ACCOUNTS[@]}"; do
        IFS=':' read -r pattern name email <<<"$account"
        local key_name="${pattern//github-/}"
        key_name="${key_name//gitlab-/}"
        local pub="$SSH_PATH/id_ed25519_$key_name.pub"

        if [ -f "$pub" ]; then
            echo -e "${GREEN}--- $name ($pattern) ---${NC}"
            cat "$pub"
            echo
        else
            print_error "Missing public key: $pub"
        fi
    done
}

# Test SSH
test_ssh_connections() {
    print_header "Step 10: Testing SSH Connections"

    for account in "${ACCOUNTS[@]}"; do
        IFS=':' read -r pattern _ _
        print_info "Testing $pattern"
        ssh -T "git@$pattern" || true
        echo
    done
}

# Usage
display_usage() {
    print_header "Setup Complete"

    for account in "${ACCOUNTS[@]}"; do
        IFS=':' read -r pattern _ _
        echo -e "${YELLOW}$pattern:${NC}"
        echo "  git clone git@$pattern:username/repo.git"
        echo
    done

    echo "Manual identity reset:"
    echo "  git set-identity"
}

# Main
main() {
    echo -e "${BLUE}
===========================================
  Git and SSH Multi-Account Setup Script
===========================================
${NC}"

    check_dependencies
    create_hooks_directory
    create_hook pre-push "Step 2: Creating Pre-Push Hook"
    create_hook pre-commit "Step 3: Creating Pre-Commit Hook"
    create_hook post-checkout "Step 4: Creating Post-Checkout Hook"
    configure_git_hooks
    add_git_alias
    generate_ssh_keys
    configure_ssh
    display_public_keys
    test_ssh_connections
    display_usage
}

main
